# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='screen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
