# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0006_auto_20171012_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
