# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0010_s1_2_s2_1_s2_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S2_1',
        ),
        migrations.DeleteModel(
            name='S2_2',
        ),
    ]
