# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0011_auto_20171013_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='screen',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixy.Slot', unique=True),
        ),
    ]
