# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0012_auto_20171013_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S1_1',
        ),
        migrations.DeleteModel(
            name='S1_2',
        ),
    ]
