# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0013_auto_20171015_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sno', models.IntegerField(max_length=2)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixy.Slot', unique=True)),
            ],
        ),
    ]
