# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 08:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0014_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixy.Slot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('slot', 'sno')]),
        ),
    ]
