# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0015_auto_20171020_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tixy.Slot'),
        ),
    ]
