# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0016_auto_20171020_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
