# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 19:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0017_remove_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sno',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
