# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixy', '0018_auto_20171031_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sno',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
